version: "3"
services:
    nginx:
        container_name: nginx
        build: . 
        restart: always
        ports:
            - "80:80"
        volumes:
            - "./grupo1:/var/www/html"
volumes:
    grupo1:
